backend:
  name: test-repo

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
    - file: "src/pages/blog/index.md"
      label: "Blog"
      name: "blog"
      create: false
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "blog-post",
          }
        - { label: "Titel", name: "title", widget: "string" }
        - { label: Bild, name: image, widget: image }
        - { label: "Rubrik till tjänst1", name: "rubrik1", widget: "string" }
        - { label: "Tjänst 1", name: "service1", widget: "text" }
        - { label: "Rubrik till tjänst 2", name: "rubrik2", widget: "string" }
        - { label: "Tjänst 2", name: "service2", widget: "text" }
        - { label: "Rubrik till tjänst 3", name: "rubrik3", widget: "string" }
        - { label: "Tjänst 3", name: "service3", widget: "text" }
        - { label: "Profil namn", name: "profil-namn", widget: "text" }
        - { label: Profil bild, name: profile-pic, widget: image }
        - { label: "Profile text", name: "profile-text", widget: "text" }
        - { label: "Profil länk", name: "profile-link", widget: "text" }
        - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
